proxy:
  host: 0.0.0.0
  port: 8080
  readTimeout: 10
  writeTimeout: 10
  # caCrt: /home/ns/.mitm/camitm.crt
  # caKey: /home/ns/.mitm/camitm.key
  caCrt: certs/caca1.crt
  caKey: certs/caca1.key
  commonName: proxy-ca-cert-cn1

repeater:
  host: 0.0.0.0
  port: 8000
  readTimeout: 10
  writeTimeout: 10

logger:
  level: debug
  encoding: json
  outputPaths: [access_log]
  errorOutputPaths: [error_log]
  messageKey: msg
  timeKey: finished
  levelKey: lvl
  namekey: name
# functionKey = "funclion"
# stacktraceKey = "stack_trace"

db:
  host: 0.0.0.0
  port: 5432
  dbname: proxy
  username: user_proxy
  password: 1111
  maxConnections: 1000
